
name: Neon
version: ${git.commit.id.abbrev}-STABLE
main: com.solexgames.hub.HubPlugin

load: STARTUP
api-version: "1.13"

author: SolexGames
website: https://www.solexgames.com

commands:
  neon:
    aliases: [setup]
  build:
    aliases: [buildmode]
